language: cpp
os: linux
dist: xenial


matrix:
    include:
        - env: CXX=g++-8
          addons:
              apt:
                  packages: ['g++-8', 'libstdc++-8-dev']
                  sources: ['ubuntu-toolchain-r-test']
        - env: CXX=clang++-8
          addons:
              apt:
                  packages: ['clang-8', 'libc++-8-dev']
                  sources: ['llvm-toolchain-xenial-8']


env:
    matrix:
        - CXX_STANDARD=11
        - CXX_STANDARD=14
        - CXX_STANDARD=17


before_script:
    - ${CXX} --version
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_STANDARD=$CXX_STANDARD ..


script:
    - make check
